services:
  - type: web
    name: rag-chatbot-backend
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: CHUTES_API_KEY
        value: cpk_cc614f8fd2a146668c59746ad8eac5cd.4b7eb952162e5bdb834624b7b92697e2.AKb67a3uzktXRINVFEYDI5Cncx22v5aD
